## Numpy

**Introdução ao Numpy**

*Autor: Danillo de Souza*

In [1]:
import numpy as np
matriz = np.array([[1,2,3], [4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

**Tipos**

In [2]:
type(matriz)

numpy.ndarray

In [3]:
matriz.dtype

dtype('int32')

**Dimensões do DataFrame**

In [4]:
matriz.shape

(2, 3)

In [5]:
matriz.size

6

**Criando Valores (Passo a passo, espaçados ou random)**

In [6]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [7]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [8]:
np.random.randint(0,30,5)

array([11,  5, 10,  9,  9])

In [9]:
matriz2 = np.random.randint(0,30,6).reshape(3,2)
matriz2

array([[12,  3],
       [20, 10],
       [14, 15]])

**Operações com Numpy**

In [10]:
matriz.max()

6

In [11]:
matriz.argmax()

5

In [12]:
matriz.min()

1

In [13]:
matriz.argmin()

0

In [14]:
matriz.mean()

3.5

In [15]:
matriz.std()

1.707825127659933

In [16]:
matriz3 = np.array([[2,4,6], [8,7,1]])
matriz3

array([[2, 4, 6],
       [8, 7, 1]])

In [17]:
matriz3.shape

(2, 3)

In [18]:
matriz + matriz3

array([[ 3,  6,  9],
       [12, 12,  7]])

In [19]:
matriz * matriz3

array([[ 2,  8, 18],
       [32, 35,  6]])

In [20]:
matriz3 ** 2 

array([[ 4, 16, 36],
       [64, 49,  1]])

**Seleção e Alteração de Valores**

In [21]:
matriz3

array([[2, 4, 6],
       [8, 7, 1]])

In [22]:
matriz3[1][1]

7

In [23]:
matriz3[0][2]

6

In [24]:
matriz3[matriz3>4]

array([6, 8, 7])

In [25]:
matriz3[1][matriz3[1]>4]

array([8, 7])

In [26]:
matriz3[1][0] = 16

In [27]:
matriz3

array([[ 2,  4,  6],
       [16,  7,  1]])

In [28]:
matriz3 = np.insert(matriz3, 1, [0,0,1], axis=0)
matriz3

array([[ 2,  4,  6],
       [ 0,  0,  1],
       [16,  7,  1]])

In [29]:
matriz3.shape

(3, 3)